#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatosMovil.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUERY_MOVIL_V2")]
	public partial class ConexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConexionDataContext() : 
				base(global::AccesoDatosMovil.Properties.Settings.Default.QUERY_MOVIL_V2ConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ACTUALIZAR_CONTRASENA")]
		public int ACTUALIZAR_CONTRASENA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(55)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA_PLAIN", DbType="NVarChar(128)")] string cONTRASENA_PLAIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEMILLA_1", DbType="NVarChar(128)")] string sEMILLA_1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEMILLA_2", DbType="NVarChar(128)")] string sEMILLA_2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, cONTRASENA_PLAIN, sEMILLA_1, sEMILLA_2, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CAMBIAR_ROL_A_VENDEDOR")]
		public ISingleResult<SP_CAMBIAR_ROL_A_VENDEDORResult> SP_CAMBIAR_ROL_A_VENDEDOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_CAMBIAR_ROL_A_VENDEDORResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_CONVERSACION")]
		public int SP_INGRESAR_CONVERSACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO2", DbType="Int")] System.Nullable<int> iD_USUARIO2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ES_SOPORTE", DbType="Bit")] System.Nullable<bool> eS_SOPORTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, iD_USUARIO2, eS_SOPORTE, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_ERROR_BACKEND")]
		public int SP_INGRESAR_ERROR_BACKEND([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo_Error", DbType="NVarChar(50)")] string codigo_Error, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="NVarChar(MAX)")] string mensaje, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Bit")] System.Nullable<bool> resultado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo_Error, mensaje, descripcion, resultado, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_HISTORIAL_VISITA")]
		public int SP_INGRESAR_HISTORIAL_VISITA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, iD_PRODUCTO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_MENSAJE")]
		public int SP_INGRESAR_MENSAJE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CONVERSACION", DbType="Int")] System.Nullable<int> iD_CONVERSACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MENSAJE", DbType="NVarChar(700)")] string mENSAJE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CONVERSACION, iD_USUARIO, mENSAJE, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTA_VERIFICACION")]
		public int SP_INSERTA_VERIFICACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(55)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODEVERIFICACION", DbType="NVarChar(10)")] string cODEVERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, cODEVERIFICACION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_FEEDBACK")]
		public int SP_INSERTAR_FEEDBACK([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CLIENTE", DbType="Int")] System.Nullable<int> iD_CLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CALIFICACION", DbType="Decimal(3,2)")] System.Nullable<decimal> cALIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COMENTARIO", DbType="NVarChar(500)")] string cOMENTARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PRODUCTO, iD_CLIENTE, cALIFICACION, cOMENTARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_PRODUCTO")]
		public ISingleResult<SP_INSERTAR_PRODUCTOResult> SP_INSERTAR_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(100)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(500)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO", DbType="Decimal(10,2)")] System.Nullable<decimal> pRECIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO_ALQUILER", DbType="Decimal(10,2)")] System.Nullable<decimal> pRECIO_ALQUILER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_OPERACION", DbType="Char(1)")] System.Nullable<char> tIPO_OPERACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STOCK", DbType="Int")] System.Nullable<int> sTOCK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CATEGORIA", DbType="NVarChar(50)")] string cATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMAGEN", DbType="VarBinary(MAX)")] System.Data.Linq.Binary iMAGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CATEGORIA", DbType="Int")] System.Nullable<int> iD_CATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DISPONIBLE", DbType="Bit")] System.Nullable<bool> dISPONIBLE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, nOMBRE, dESCRIPCION, pRECIO, pRECIO_ALQUILER, tIPO_OPERACION, sTOCK, cATEGORIA, iMAGEN, iD_CATEGORIA, dISPONIBLE, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(11)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(12)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(13)));
			return ((ISingleResult<SP_INSERTAR_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_CONVERSACIONES")]
		public ISingleResult<SP_LISTAR_CONVERSACIONESResult> SP_LISTAR_CONVERSACIONES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_LISTAR_CONVERSACIONESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_MENSAJES")]
		public ISingleResult<SP_LISTAR_MENSAJESResult> SP_LISTAR_MENSAJES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CONVERSACION", DbType="Int")] System.Nullable<int> iD_CONVERSACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CONVERSACION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_LISTAR_MENSAJESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_PRODUCTO")]
		public ISingleResult<SP_LISTAR_PRODUCTOResult> SP_LISTAR_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(0)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_LISTAR_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_PRODUCTOS_FILTRADOS")]
		public ISingleResult<SP_LISTAR_PRODUCTOS_FILTRADOSResult> SP_LISTAR_PRODUCTOS_FILTRADOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_OPERACION", DbType="Char(1)")] System.Nullable<char> tIPO_OPERACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PALABRA_CLAVE", DbType="NVarChar(100)")] string pALABRA_CLAVE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO_OPERACION, pALABRA_CLAVE, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_LISTAR_PRODUCTOS_FILTRADOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_PRODUCTOS_RANDOM")]
		public ISingleResult<SP_LISTAR_PRODUCTOS_RANDOMResult> SP_LISTAR_PRODUCTOS_RANDOM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(0)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_LISTAR_PRODUCTOS_RANDOMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN_USUARIO")]
		public ISingleResult<SP_LOGIN_USUARIOResult> SP_LOGIN_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(55)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_LOGIN_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MAPA")]
		public ISingleResult<SP_MAPAResult> SP_MAPA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RADIO_KM", DbType="Float")] System.Nullable<double> rADIO_KM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, rADIO_KM, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_MAPAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_CONVERSACION")]
		public ISingleResult<SP_OBTENER_CONVERSACIONResult> SP_OBTENER_CONVERSACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CONVERSACION", DbType="Int")] System.Nullable<int> iD_CONVERSACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CONVERSACION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_CONVERSACIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_FEEDBACK")]
		public ISingleResult<SP_OBTENER_FEEDBACKResult> SP_OBTENER_FEEDBACK([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PRODUCTO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_FEEDBACKResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_HISTORIAL_VISITAS")]
		public ISingleResult<SP_OBTENER_HISTORIAL_VISITASResult> SP_OBTENER_HISTORIAL_VISITAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_HISTORIAL_VISITASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PRODUCTO")]
		public ISingleResult<SP_OBTENER_PRODUCTOResult> SP_OBTENER_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRODUCTO", DbType="Int")] System.Nullable<int> iD_PRODUCTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PRODUCTO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_USUARIO")]
		public ISingleResult<SP_OBTENER_USUARIOResult> SP_OBTENER_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_VERIFICACION")]
		public ISingleResult<SP_OBTENER_VERIFICACIONResult> SP_OBTENER_VERIFICACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(55)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_VERIFICACIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PRODUCTOS_BUSCADOS")]
		public ISingleResult<SP_PRODUCTOS_BUSCADOSResult> SP_PRODUCTOS_BUSCADOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TEXTO_BUSQUEDA", DbType="NVarChar(100)")] string tEXTO_BUSQUEDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tEXTO_BUSQUEDA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_PRODUCTOS_BUSCADOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REGISTRAR_USUARIO")]
		public int SP_REGISTRAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(55)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="NVarChar(15)")] string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ROL", DbType="NVarChar(20)")] string rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="NVarChar(128)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEMILLA_1", DbType="NVarChar(128)")] string sEMILLA_1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEMILLA_2", DbType="NVarChar(128)")] string sEMILLA_2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LATITUD", DbType="Float")] System.Nullable<double> lATITUD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LONGITUD", DbType="Float")] System.Nullable<double> lONGITUD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO", DbType="Bit")] System.Nullable<bool> eSTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] ref System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, cORREO, tELEFONO, rOL, cONTRASENA, sEMILLA_1, sEMILLA_2, lATITUD, lONGITUD, eSTADO, iD_USUARIO, eRRORID, eRRORDESCRIPCION);
			iD_USUARIO = ((System.Nullable<int>)(result.GetParameterValue(10)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(11)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(12)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VERIFICACION_COMPLETADA")]
		public ISingleResult<SP_VERIFICACION_COMPLETADAResult> SP_VERIFICACION_COMPLETADA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_VERIFICACION", DbType="Int")] System.Nullable<int> iD_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(55)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO", DbType="Bit")] System.Nullable<bool> eSTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_VERIFICACION, cORREO, eSTADO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((ISingleResult<SP_VERIFICACION_COMPLETADAResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_CAMBIAR_ROL_A_VENDEDORResult
	{
		
		private int _ID_USUARIO;
		
		private int _ID_PERSONA;
		
		private string _NOMBRE;
		
		private string _CORREO;
		
		private string _TELEFONO;
		
		private string _UBICACION_STRING;
		
		private System.Nullable<System.DateTime> _FECHA_REGISTRO;
		
		private string _ROL;
		
		private System.Nullable<bool> _ESTADO;
		
		private System.Nullable<System.DateTime> _FECHA_ULTIMA_COMPRA;
		
		private System.Nullable<double> _LONGITUD;
		
		private System.Nullable<double> _LATITUD;
		
		public SP_CAMBIAR_ROL_A_VENDEDORResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERSONA", DbType="Int NOT NULL")]
		public int ID_PERSONA
		{
			get
			{
				return this._ID_PERSONA;
			}
			set
			{
				if ((this._ID_PERSONA != value))
				{
					this._ID_PERSONA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(15)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UBICACION_STRING", DbType="NVarChar(MAX)")]
		public string UBICACION_STRING
		{
			get
			{
				return this._UBICACION_STRING;
			}
			set
			{
				if ((this._UBICACION_STRING != value))
				{
					this._UBICACION_STRING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit")]
		public System.Nullable<bool> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ULTIMA_COMPRA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ULTIMA_COMPRA
		{
			get
			{
				return this._FECHA_ULTIMA_COMPRA;
			}
			set
			{
				if ((this._FECHA_ULTIMA_COMPRA != value))
				{
					this._FECHA_ULTIMA_COMPRA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD", DbType="Float")]
		public System.Nullable<double> LONGITUD
		{
			get
			{
				return this._LONGITUD;
			}
			set
			{
				if ((this._LONGITUD != value))
				{
					this._LONGITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD", DbType="Float")]
		public System.Nullable<double> LATITUD
		{
			get
			{
				return this._LATITUD;
			}
			set
			{
				if ((this._LATITUD != value))
				{
					this._LATITUD = value;
				}
			}
		}
	}
	
	public partial class SP_INSERTAR_PRODUCTOResult
	{
		
		private int _ID_PRODUCTO;
		
		private int _ID_USUARIO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private decimal _PRECIO;
		
		private System.Nullable<decimal> _PRECIO_ALQUILER;
		
		private System.Nullable<char> _TIPO_OPERACION;
		
		private System.Nullable<int> _STOCK;
		
		private System.Nullable<bool> _DISPONIBLE;
		
		private System.Nullable<decimal> _CALIFICACION_PROMEDIO;
		
		private System.Nullable<System.DateTime> _FECHA_PUBLICACION;
		
		private System.Data.Linq.Binary _IMAGEN;
		
		private string _CATEGORIA;
		
		private System.Nullable<int> _ID_CATEGORIA;
		
		public SP_INSERTAR_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(500)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(10,2) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_ALQUILER", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PRECIO_ALQUILER
		{
			get
			{
				return this._PRECIO_ALQUILER;
			}
			set
			{
				if ((this._PRECIO_ALQUILER != value))
				{
					this._PRECIO_ALQUILER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_OPERACION", DbType="Char(1)")]
		public System.Nullable<char> TIPO_OPERACION
		{
			get
			{
				return this._TIPO_OPERACION;
			}
			set
			{
				if ((this._TIPO_OPERACION != value))
				{
					this._TIPO_OPERACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK", DbType="Int")]
		public System.Nullable<int> STOCK
		{
			get
			{
				return this._STOCK;
			}
			set
			{
				if ((this._STOCK != value))
				{
					this._STOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPONIBLE", DbType="Bit")]
		public System.Nullable<bool> DISPONIBLE
		{
			get
			{
				return this._DISPONIBLE;
			}
			set
			{
				if ((this._DISPONIBLE != value))
				{
					this._DISPONIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALIFICACION_PROMEDIO", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> CALIFICACION_PROMEDIO
		{
			get
			{
				return this._CALIFICACION_PROMEDIO;
			}
			set
			{
				if ((this._CALIFICACION_PROMEDIO != value))
				{
					this._CALIFICACION_PROMEDIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PUBLICACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_PUBLICACION
		{
			get
			{
				return this._FECHA_PUBLICACION;
			}
			set
			{
				if ((this._FECHA_PUBLICACION != value))
				{
					this._FECHA_PUBLICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary IMAGEN
		{
			get
			{
				return this._IMAGEN;
			}
			set
			{
				if ((this._IMAGEN != value))
				{
					this._IMAGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA", DbType="NVarChar(50)")]
		public string CATEGORIA
		{
			get
			{
				return this._CATEGORIA;
			}
			set
			{
				if ((this._CATEGORIA != value))
				{
					this._CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORIA", DbType="Int")]
		public System.Nullable<int> ID_CATEGORIA
		{
			get
			{
				return this._ID_CATEGORIA;
			}
			set
			{
				if ((this._ID_CATEGORIA != value))
				{
					this._ID_CATEGORIA = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_CONVERSACIONESResult
	{
		
		private int _ID_CONVERSACION;
		
		private int _ID_USUARIO1;
		
		private int _ID_USUARIO2;
		
		private System.Nullable<bool> _ES_SOPORTE;
		
		private System.Nullable<System.DateTime> _FECHA_CREACION;
		
		public SP_LISTAR_CONVERSACIONESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONVERSACION", DbType="Int NOT NULL")]
		public int ID_CONVERSACION
		{
			get
			{
				return this._ID_CONVERSACION;
			}
			set
			{
				if ((this._ID_CONVERSACION != value))
				{
					this._ID_CONVERSACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO1", DbType="Int NOT NULL")]
		public int ID_USUARIO1
		{
			get
			{
				return this._ID_USUARIO1;
			}
			set
			{
				if ((this._ID_USUARIO1 != value))
				{
					this._ID_USUARIO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO2", DbType="Int NOT NULL")]
		public int ID_USUARIO2
		{
			get
			{
				return this._ID_USUARIO2;
			}
			set
			{
				if ((this._ID_USUARIO2 != value))
				{
					this._ID_USUARIO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ES_SOPORTE", DbType="Bit")]
		public System.Nullable<bool> ES_SOPORTE
		{
			get
			{
				return this._ES_SOPORTE;
			}
			set
			{
				if ((this._ES_SOPORTE != value))
				{
					this._ES_SOPORTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_CREACION
		{
			get
			{
				return this._FECHA_CREACION;
			}
			set
			{
				if ((this._FECHA_CREACION != value))
				{
					this._FECHA_CREACION = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_MENSAJESResult
	{
		
		private int _ID_MENSAJES;
		
		private int _ID_CONVERSACION;
		
		private int _ID_USUARIO;
		
		private string _NOMBRE_USUARIO;
		
		private string _MENSAJE;
		
		private System.Nullable<System.DateTime> _FECHA_CREACION;
		
		public SP_LISTAR_MENSAJESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MENSAJES", DbType="Int NOT NULL")]
		public int ID_MENSAJES
		{
			get
			{
				return this._ID_MENSAJES;
			}
			set
			{
				if ((this._ID_MENSAJES != value))
				{
					this._ID_MENSAJES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONVERSACION", DbType="Int NOT NULL")]
		public int ID_CONVERSACION
		{
			get
			{
				return this._ID_CONVERSACION;
			}
			set
			{
				if ((this._ID_CONVERSACION != value))
				{
					this._ID_CONVERSACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USUARIO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_USUARIO
		{
			get
			{
				return this._NOMBRE_USUARIO;
			}
			set
			{
				if ((this._NOMBRE_USUARIO != value))
				{
					this._NOMBRE_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENSAJE", DbType="NVarChar(700) NOT NULL", CanBeNull=false)]
		public string MENSAJE
		{
			get
			{
				return this._MENSAJE;
			}
			set
			{
				if ((this._MENSAJE != value))
				{
					this._MENSAJE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_CREACION
		{
			get
			{
				return this._FECHA_CREACION;
			}
			set
			{
				if ((this._FECHA_CREACION != value))
				{
					this._FECHA_CREACION = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_PRODUCTOResult
	{
		
		private int _ID_PRODUCTO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private decimal _PRECIO;
		
		private System.Nullable<decimal> _PRECIO_ALQUILER;
		
		private System.Nullable<int> _STOCK;
		
		private System.Nullable<char> _TIPO_OPERACION;
		
		private System.Nullable<decimal> _CALIFICACION_PROMEDIO;
		
		private System.Nullable<System.DateTime> _FECHA_PUBLICACION;
		
		private System.Nullable<bool> _DISPONIBLE;
		
		private int _ID_USUARIO;
		
		private string _CATEGORIA;
		
		private System.Data.Linq.Binary _IMAGEN;
		
		public SP_LISTAR_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(500)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(10,2) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_ALQUILER", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PRECIO_ALQUILER
		{
			get
			{
				return this._PRECIO_ALQUILER;
			}
			set
			{
				if ((this._PRECIO_ALQUILER != value))
				{
					this._PRECIO_ALQUILER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK", DbType="Int")]
		public System.Nullable<int> STOCK
		{
			get
			{
				return this._STOCK;
			}
			set
			{
				if ((this._STOCK != value))
				{
					this._STOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_OPERACION", DbType="Char(1)")]
		public System.Nullable<char> TIPO_OPERACION
		{
			get
			{
				return this._TIPO_OPERACION;
			}
			set
			{
				if ((this._TIPO_OPERACION != value))
				{
					this._TIPO_OPERACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALIFICACION_PROMEDIO", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> CALIFICACION_PROMEDIO
		{
			get
			{
				return this._CALIFICACION_PROMEDIO;
			}
			set
			{
				if ((this._CALIFICACION_PROMEDIO != value))
				{
					this._CALIFICACION_PROMEDIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PUBLICACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_PUBLICACION
		{
			get
			{
				return this._FECHA_PUBLICACION;
			}
			set
			{
				if ((this._FECHA_PUBLICACION != value))
				{
					this._FECHA_PUBLICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPONIBLE", DbType="Bit")]
		public System.Nullable<bool> DISPONIBLE
		{
			get
			{
				return this._DISPONIBLE;
			}
			set
			{
				if ((this._DISPONIBLE != value))
				{
					this._DISPONIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA", DbType="NVarChar(50)")]
		public string CATEGORIA
		{
			get
			{
				return this._CATEGORIA;
			}
			set
			{
				if ((this._CATEGORIA != value))
				{
					this._CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary IMAGEN
		{
			get
			{
				return this._IMAGEN;
			}
			set
			{
				if ((this._IMAGEN != value))
				{
					this._IMAGEN = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_PRODUCTOS_FILTRADOSResult
	{
		
		private int _ID_PRODUCTO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private decimal _PRECIO;
		
		private System.Nullable<decimal> _PRECIO_ALQUILER;
		
		private System.Nullable<int> _STOCK;
		
		private System.Nullable<char> _TIPO_OPERACION;
		
		private System.Nullable<decimal> _CALIFICACION_PROMEDIO;
		
		private System.Nullable<System.DateTime> _FECHA_PUBLICACION;
		
		private int _ID_USUARIO;
		
		private string _CATEGORIA;
		
		private System.Data.Linq.Binary _IMAGEN;
		
		public SP_LISTAR_PRODUCTOS_FILTRADOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(500)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(10,2) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_ALQUILER", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PRECIO_ALQUILER
		{
			get
			{
				return this._PRECIO_ALQUILER;
			}
			set
			{
				if ((this._PRECIO_ALQUILER != value))
				{
					this._PRECIO_ALQUILER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK", DbType="Int")]
		public System.Nullable<int> STOCK
		{
			get
			{
				return this._STOCK;
			}
			set
			{
				if ((this._STOCK != value))
				{
					this._STOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_OPERACION", DbType="Char(1)")]
		public System.Nullable<char> TIPO_OPERACION
		{
			get
			{
				return this._TIPO_OPERACION;
			}
			set
			{
				if ((this._TIPO_OPERACION != value))
				{
					this._TIPO_OPERACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALIFICACION_PROMEDIO", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> CALIFICACION_PROMEDIO
		{
			get
			{
				return this._CALIFICACION_PROMEDIO;
			}
			set
			{
				if ((this._CALIFICACION_PROMEDIO != value))
				{
					this._CALIFICACION_PROMEDIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PUBLICACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_PUBLICACION
		{
			get
			{
				return this._FECHA_PUBLICACION;
			}
			set
			{
				if ((this._FECHA_PUBLICACION != value))
				{
					this._FECHA_PUBLICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA", DbType="NVarChar(50)")]
		public string CATEGORIA
		{
			get
			{
				return this._CATEGORIA;
			}
			set
			{
				if ((this._CATEGORIA != value))
				{
					this._CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary IMAGEN
		{
			get
			{
				return this._IMAGEN;
			}
			set
			{
				if ((this._IMAGEN != value))
				{
					this._IMAGEN = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_PRODUCTOS_RANDOMResult
	{
		
		private int _ID_PRODUCTO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private decimal _PRECIO;
		
		private System.Nullable<decimal> _PRECIO_ALQUILER;
		
		private System.Nullable<int> _STOCK;
		
		private System.Nullable<char> _TIPO_OPERACION;
		
		private System.Nullable<decimal> _CALIFICACION_PROMEDIO;
		
		private System.Nullable<System.DateTime> _FECHA_PUBLICACION;
		
		private System.Nullable<bool> _DISPONIBLE;
		
		private int _ID_USUARIO;
		
		private string _CATEGORIA;
		
		private System.Data.Linq.Binary _IMAGEN;
		
		private System.Nullable<int> _ID_CATEGORIA;
		
		public SP_LISTAR_PRODUCTOS_RANDOMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(500)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(10,2) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_ALQUILER", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PRECIO_ALQUILER
		{
			get
			{
				return this._PRECIO_ALQUILER;
			}
			set
			{
				if ((this._PRECIO_ALQUILER != value))
				{
					this._PRECIO_ALQUILER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK", DbType="Int")]
		public System.Nullable<int> STOCK
		{
			get
			{
				return this._STOCK;
			}
			set
			{
				if ((this._STOCK != value))
				{
					this._STOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_OPERACION", DbType="Char(1)")]
		public System.Nullable<char> TIPO_OPERACION
		{
			get
			{
				return this._TIPO_OPERACION;
			}
			set
			{
				if ((this._TIPO_OPERACION != value))
				{
					this._TIPO_OPERACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALIFICACION_PROMEDIO", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> CALIFICACION_PROMEDIO
		{
			get
			{
				return this._CALIFICACION_PROMEDIO;
			}
			set
			{
				if ((this._CALIFICACION_PROMEDIO != value))
				{
					this._CALIFICACION_PROMEDIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PUBLICACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_PUBLICACION
		{
			get
			{
				return this._FECHA_PUBLICACION;
			}
			set
			{
				if ((this._FECHA_PUBLICACION != value))
				{
					this._FECHA_PUBLICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPONIBLE", DbType="Bit")]
		public System.Nullable<bool> DISPONIBLE
		{
			get
			{
				return this._DISPONIBLE;
			}
			set
			{
				if ((this._DISPONIBLE != value))
				{
					this._DISPONIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA", DbType="NVarChar(50)")]
		public string CATEGORIA
		{
			get
			{
				return this._CATEGORIA;
			}
			set
			{
				if ((this._CATEGORIA != value))
				{
					this._CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary IMAGEN
		{
			get
			{
				return this._IMAGEN;
			}
			set
			{
				if ((this._IMAGEN != value))
				{
					this._IMAGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORIA", DbType="Int")]
		public System.Nullable<int> ID_CATEGORIA
		{
			get
			{
				return this._ID_CATEGORIA;
			}
			set
			{
				if ((this._ID_CATEGORIA != value))
				{
					this._ID_CATEGORIA = value;
				}
			}
		}
	}
	
	public partial class SP_LOGIN_USUARIOResult
	{
		
		private System.Nullable<int> _ID_USUARIO;
		
		private System.Nullable<int> _ID_PERSONA;
		
		private string _NOMBRE;
		
		private string _CORREO;
		
		private string _TELEFONO;
		
		private string _UBICACION_STRING;
		
		private System.Nullable<double> _LATITUD;
		
		private System.Nullable<double> _LONGITUD;
		
		private string _ROL;
		
		private System.Nullable<bool> _ESTADO;
		
		private System.Nullable<System.DateTime> _FECHA_ULTIMA_COMPRA;
		
		private string _SEMILLA_1;
		
		private string _SEMILLA_2;
		
		private string _CONTRASENA;
		
		public SP_LOGIN_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int")]
		public System.Nullable<int> ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERSONA", DbType="Int")]
		public System.Nullable<int> ID_PERSONA
		{
			get
			{
				return this._ID_PERSONA;
			}
			set
			{
				if ((this._ID_PERSONA != value))
				{
					this._ID_PERSONA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="NVarChar(55)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(15)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UBICACION_STRING", DbType="NVarChar(MAX)")]
		public string UBICACION_STRING
		{
			get
			{
				return this._UBICACION_STRING;
			}
			set
			{
				if ((this._UBICACION_STRING != value))
				{
					this._UBICACION_STRING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD", DbType="Float")]
		public System.Nullable<double> LATITUD
		{
			get
			{
				return this._LATITUD;
			}
			set
			{
				if ((this._LATITUD != value))
				{
					this._LATITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD", DbType="Float")]
		public System.Nullable<double> LONGITUD
		{
			get
			{
				return this._LONGITUD;
			}
			set
			{
				if ((this._LONGITUD != value))
				{
					this._LONGITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL", DbType="NVarChar(20)")]
		public string ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit")]
		public System.Nullable<bool> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ULTIMA_COMPRA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ULTIMA_COMPRA
		{
			get
			{
				return this._FECHA_ULTIMA_COMPRA;
			}
			set
			{
				if ((this._FECHA_ULTIMA_COMPRA != value))
				{
					this._FECHA_ULTIMA_COMPRA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMILLA_1", DbType="NVarChar(128)")]
		public string SEMILLA_1
		{
			get
			{
				return this._SEMILLA_1;
			}
			set
			{
				if ((this._SEMILLA_1 != value))
				{
					this._SEMILLA_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMILLA_2", DbType="NVarChar(128)")]
		public string SEMILLA_2
		{
			get
			{
				return this._SEMILLA_2;
			}
			set
			{
				if ((this._SEMILLA_2 != value))
				{
					this._SEMILLA_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRASENA", DbType="NVarChar(MAX)")]
		public string CONTRASENA
		{
			get
			{
				return this._CONTRASENA;
			}
			set
			{
				if ((this._CONTRASENA != value))
				{
					this._CONTRASENA = value;
				}
			}
		}
	}
	
	public partial class SP_MAPAResult
	{
		
		private int _ID_USUARIO;
		
		private string _NOMBRE;
		
		private string _CORREO;
		
		private string _TELEFONO;
		
		private System.Nullable<double> _LATITUD;
		
		private System.Nullable<double> _LONGITUD;
		
		private System.Nullable<double> _DISTANCIA_KM;
		
		private string _ROL;
		
		private System.Nullable<bool> _ESTADO;
		
		public SP_MAPAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(15)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD", DbType="Float")]
		public System.Nullable<double> LATITUD
		{
			get
			{
				return this._LATITUD;
			}
			set
			{
				if ((this._LATITUD != value))
				{
					this._LATITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD", DbType="Float")]
		public System.Nullable<double> LONGITUD
		{
			get
			{
				return this._LONGITUD;
			}
			set
			{
				if ((this._LONGITUD != value))
				{
					this._LONGITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTANCIA_KM", DbType="Float")]
		public System.Nullable<double> DISTANCIA_KM
		{
			get
			{
				return this._DISTANCIA_KM;
			}
			set
			{
				if ((this._DISTANCIA_KM != value))
				{
					this._DISTANCIA_KM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit")]
		public System.Nullable<bool> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_CONVERSACIONResult
	{
		
		private int _ID_CONVERSACION;
		
		private int _ID_USUARIO1;
		
		private int _ID_USUARIO2;
		
		private System.Nullable<bool> _ES_SOPORTE;
		
		private System.Nullable<System.DateTime> _FECHA_CREACION;
		
		public SP_OBTENER_CONVERSACIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONVERSACION", DbType="Int NOT NULL")]
		public int ID_CONVERSACION
		{
			get
			{
				return this._ID_CONVERSACION;
			}
			set
			{
				if ((this._ID_CONVERSACION != value))
				{
					this._ID_CONVERSACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO1", DbType="Int NOT NULL")]
		public int ID_USUARIO1
		{
			get
			{
				return this._ID_USUARIO1;
			}
			set
			{
				if ((this._ID_USUARIO1 != value))
				{
					this._ID_USUARIO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO2", DbType="Int NOT NULL")]
		public int ID_USUARIO2
		{
			get
			{
				return this._ID_USUARIO2;
			}
			set
			{
				if ((this._ID_USUARIO2 != value))
				{
					this._ID_USUARIO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ES_SOPORTE", DbType="Bit")]
		public System.Nullable<bool> ES_SOPORTE
		{
			get
			{
				return this._ES_SOPORTE;
			}
			set
			{
				if ((this._ES_SOPORTE != value))
				{
					this._ES_SOPORTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_CREACION
		{
			get
			{
				return this._FECHA_CREACION;
			}
			set
			{
				if ((this._FECHA_CREACION != value))
				{
					this._FECHA_CREACION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_FEEDBACKResult
	{
		
		private int _ID_FEEDBACK;
		
		private int _ID_PRODUCTO;
		
		private string _NOMBRE_PRODUCTO;
		
		private int _ID_USUARIO;
		
		private decimal _CALIFICACION;
		
		private string _COMENTARIO;
		
		private System.Nullable<System.DateTime> _FECHA_FEEDBACK;
		
		public SP_OBTENER_FEEDBACKResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FEEDBACK", DbType="Int NOT NULL")]
		public int ID_FEEDBACK
		{
			get
			{
				return this._ID_FEEDBACK;
			}
			set
			{
				if ((this._ID_FEEDBACK != value))
				{
					this._ID_FEEDBACK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PRODUCTO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE_PRODUCTO
		{
			get
			{
				return this._NOMBRE_PRODUCTO;
			}
			set
			{
				if ((this._NOMBRE_PRODUCTO != value))
				{
					this._NOMBRE_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALIFICACION", DbType="Decimal(3,2) NOT NULL")]
		public decimal CALIFICACION
		{
			get
			{
				return this._CALIFICACION;
			}
			set
			{
				if ((this._CALIFICACION != value))
				{
					this._CALIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMENTARIO", DbType="NVarChar(500)")]
		public string COMENTARIO
		{
			get
			{
				return this._COMENTARIO;
			}
			set
			{
				if ((this._COMENTARIO != value))
				{
					this._COMENTARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_FEEDBACK", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_FEEDBACK
		{
			get
			{
				return this._FECHA_FEEDBACK;
			}
			set
			{
				if ((this._FECHA_FEEDBACK != value))
				{
					this._FECHA_FEEDBACK = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_HISTORIAL_VISITASResult
	{
		
		private int _ID_HISTORIAL_VISITAS;
		
		private int _ID_USUARIO;
		
		private int _ID_PRODUCTO;
		
		private string _NOMBRE_PRODUCTO;
		
		private System.Nullable<System.DateTime> _FECHA_VISTA;
		
		public SP_OBTENER_HISTORIAL_VISITASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HISTORIAL_VISITAS", DbType="Int NOT NULL")]
		public int ID_HISTORIAL_VISITAS
		{
			get
			{
				return this._ID_HISTORIAL_VISITAS;
			}
			set
			{
				if ((this._ID_HISTORIAL_VISITAS != value))
				{
					this._ID_HISTORIAL_VISITAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PRODUCTO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE_PRODUCTO
		{
			get
			{
				return this._NOMBRE_PRODUCTO;
			}
			set
			{
				if ((this._NOMBRE_PRODUCTO != value))
				{
					this._NOMBRE_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_VISTA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_VISTA
		{
			get
			{
				return this._FECHA_VISTA;
			}
			set
			{
				if ((this._FECHA_VISTA != value))
				{
					this._FECHA_VISTA = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PRODUCTOResult
	{
		
		private int _ID_PRODUCTO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private decimal _PRECIO;
		
		private System.Nullable<decimal> _PRECIO_ALQUILER;
		
		private System.Nullable<int> _STOCK;
		
		private System.Nullable<char> _TIPO_OPERACION;
		
		private System.Nullable<decimal> _CALIFICACION_PROMEDIO;
		
		private System.Nullable<System.DateTime> _FECHA_PUBLICACION;
		
		private System.Nullable<bool> _DISPONIBLE;
		
		private int _ID_USUARIO;
		
		private string _CATEGORIA;
		
		private System.Data.Linq.Binary _IMAGEN;
		
		public SP_OBTENER_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(500)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(10,2) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_ALQUILER", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PRECIO_ALQUILER
		{
			get
			{
				return this._PRECIO_ALQUILER;
			}
			set
			{
				if ((this._PRECIO_ALQUILER != value))
				{
					this._PRECIO_ALQUILER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK", DbType="Int")]
		public System.Nullable<int> STOCK
		{
			get
			{
				return this._STOCK;
			}
			set
			{
				if ((this._STOCK != value))
				{
					this._STOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_OPERACION", DbType="Char(1)")]
		public System.Nullable<char> TIPO_OPERACION
		{
			get
			{
				return this._TIPO_OPERACION;
			}
			set
			{
				if ((this._TIPO_OPERACION != value))
				{
					this._TIPO_OPERACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALIFICACION_PROMEDIO", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> CALIFICACION_PROMEDIO
		{
			get
			{
				return this._CALIFICACION_PROMEDIO;
			}
			set
			{
				if ((this._CALIFICACION_PROMEDIO != value))
				{
					this._CALIFICACION_PROMEDIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PUBLICACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_PUBLICACION
		{
			get
			{
				return this._FECHA_PUBLICACION;
			}
			set
			{
				if ((this._FECHA_PUBLICACION != value))
				{
					this._FECHA_PUBLICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPONIBLE", DbType="Bit")]
		public System.Nullable<bool> DISPONIBLE
		{
			get
			{
				return this._DISPONIBLE;
			}
			set
			{
				if ((this._DISPONIBLE != value))
				{
					this._DISPONIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA", DbType="NVarChar(50)")]
		public string CATEGORIA
		{
			get
			{
				return this._CATEGORIA;
			}
			set
			{
				if ((this._CATEGORIA != value))
				{
					this._CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary IMAGEN
		{
			get
			{
				return this._IMAGEN;
			}
			set
			{
				if ((this._IMAGEN != value))
				{
					this._IMAGEN = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_USUARIOResult
	{
		
		private int _IdUsuario;
		
		private int _IdPersona;
		
		private string _NOMBRE;
		
		private string _CORREO;
		
		private string _TELEFONO;
		
		private string _UBICACION;
		
		private System.Nullable<double> _LATITUD;
		
		private System.Nullable<double> _LONGITUD;
		
		private string _ROL;
		
		private System.Nullable<bool> _ESTADO;
		
		public SP_OBTENER_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", DbType="Int NOT NULL")]
		public int IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					this._IdPersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(15)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UBICACION", DbType="NVarChar(MAX)")]
		public string UBICACION
		{
			get
			{
				return this._UBICACION;
			}
			set
			{
				if ((this._UBICACION != value))
				{
					this._UBICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD", DbType="Float")]
		public System.Nullable<double> LATITUD
		{
			get
			{
				return this._LATITUD;
			}
			set
			{
				if ((this._LATITUD != value))
				{
					this._LATITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD", DbType="Float")]
		public System.Nullable<double> LONGITUD
		{
			get
			{
				return this._LONGITUD;
			}
			set
			{
				if ((this._LONGITUD != value))
				{
					this._LONGITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit")]
		public System.Nullable<bool> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_VERIFICACIONResult
	{
		
		private int _ID_VERIFICACION;
		
		private string _CORREO;
		
		private string _CODEVERIFICACION;
		
		private System.Nullable<System.DateTime> _FECHA_REGISTRO;
		
		public SP_OBTENER_VERIFICACIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VERIFICACION", DbType="Int NOT NULL")]
		public int ID_VERIFICACION
		{
			get
			{
				return this._ID_VERIFICACION;
			}
			set
			{
				if ((this._ID_VERIFICACION != value))
				{
					this._ID_VERIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEVERIFICACION", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string CODEVERIFICACION
		{
			get
			{
				return this._CODEVERIFICACION;
			}
			set
			{
				if ((this._CODEVERIFICACION != value))
				{
					this._CODEVERIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
	}
	
	public partial class SP_PRODUCTOS_BUSCADOSResult
	{
		
		private int _ID_PRODUCTO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private decimal _PRECIO;
		
		private System.Nullable<decimal> _PRECIO_ALQUILER;
		
		private System.Nullable<int> _STOCK;
		
		private System.Nullable<char> _TIPO_OPERACION;
		
		private System.Nullable<decimal> _CALIFICACION_PROMEDIO;
		
		private System.Nullable<System.DateTime> _FECHA_PUBLICACION;
		
		private int _ID_USUARIO;
		
		private string _CATEGORIA;
		
		private System.Data.Linq.Binary _IMAGEN;
		
		private System.Nullable<bool> _DISPONIBLE;
		
		public SP_PRODUCTOS_BUSCADOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", DbType="Int NOT NULL")]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this._ID_PRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(500)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(10,2) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_ALQUILER", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PRECIO_ALQUILER
		{
			get
			{
				return this._PRECIO_ALQUILER;
			}
			set
			{
				if ((this._PRECIO_ALQUILER != value))
				{
					this._PRECIO_ALQUILER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK", DbType="Int")]
		public System.Nullable<int> STOCK
		{
			get
			{
				return this._STOCK;
			}
			set
			{
				if ((this._STOCK != value))
				{
					this._STOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_OPERACION", DbType="Char(1)")]
		public System.Nullable<char> TIPO_OPERACION
		{
			get
			{
				return this._TIPO_OPERACION;
			}
			set
			{
				if ((this._TIPO_OPERACION != value))
				{
					this._TIPO_OPERACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALIFICACION_PROMEDIO", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> CALIFICACION_PROMEDIO
		{
			get
			{
				return this._CALIFICACION_PROMEDIO;
			}
			set
			{
				if ((this._CALIFICACION_PROMEDIO != value))
				{
					this._CALIFICACION_PROMEDIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PUBLICACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_PUBLICACION
		{
			get
			{
				return this._FECHA_PUBLICACION;
			}
			set
			{
				if ((this._FECHA_PUBLICACION != value))
				{
					this._FECHA_PUBLICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA", DbType="NVarChar(50)")]
		public string CATEGORIA
		{
			get
			{
				return this._CATEGORIA;
			}
			set
			{
				if ((this._CATEGORIA != value))
				{
					this._CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary IMAGEN
		{
			get
			{
				return this._IMAGEN;
			}
			set
			{
				if ((this._IMAGEN != value))
				{
					this._IMAGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPONIBLE", DbType="Bit")]
		public System.Nullable<bool> DISPONIBLE
		{
			get
			{
				return this._DISPONIBLE;
			}
			set
			{
				if ((this._DISPONIBLE != value))
				{
					this._DISPONIBLE = value;
				}
			}
		}
	}
	
	public partial class SP_VERIFICACION_COMPLETADAResult
	{
		
		private int _ID_VERIFICACION;
		
		private string _CORREO;
		
		private string _CODEVERIFICACION;
		
		private System.Nullable<System.DateTime> _FECHA_REGISTRO;
		
		private System.Nullable<bool> _ESTADO_PROCESADO;
		
		public SP_VERIFICACION_COMPLETADAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VERIFICACION", DbType="Int NOT NULL")]
		public int ID_VERIFICACION
		{
			get
			{
				return this._ID_VERIFICACION;
			}
			set
			{
				if ((this._ID_VERIFICACION != value))
				{
					this._ID_VERIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEVERIFICACION", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string CODEVERIFICACION
		{
			get
			{
				return this._CODEVERIFICACION;
			}
			set
			{
				if ((this._CODEVERIFICACION != value))
				{
					this._CODEVERIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_PROCESADO", DbType="Bit")]
		public System.Nullable<bool> ESTADO_PROCESADO
		{
			get
			{
				return this._ESTADO_PROCESADO;
			}
			set
			{
				if ((this._ESTADO_PROCESADO != value))
				{
					this._ESTADO_PROCESADO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
