USE QUERY_MOVIL_V2;
GO
-- Eliminar las tablas sin preocuparse por las dependencias
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_MENSAJES_CHATS')
    DROP TABLE TB_MENSAJES_CHATS;
GO
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_CHATS')
    DROP TABLE TB_CHATS;
GO
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_RESPUESTAS_TICKETS')
    DROP TABLE TB_RESPUESTAS_TICKETS;
GO
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_TICKETS')
    DROP TABLE TB_TICKETS;
GO
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_SOPORTES_CATEGORIAS')
    DROP TABLE TB_SOPORTES_CATEGORIAS;
GO
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TM_TICKETS')
    DROP TABLE TM_TICKETS;
GO
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'RESPUESTA_PUBLICACION')
    DROP TABLE RESPUESTA_PUBLICACION;
GO
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_PUBLICACIONES')
    DROP TABLE TB_PUBLICACIONES;
GO
-- Eliminar SP_GUARDAR_ID_PRODUCTO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_GUARDAR_ID_PRODUCTO'))
    DROP PROCEDURE SP_GUARDAR_ID_PRODUCTO;
GO
-- Eliminar SP_INGRESAR_VISITA
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INGRESAR_VISITA'))
    DROP PROCEDURE SP_INGRESAR_VISITA;
GO
-- Eliminar SP_OBTENER_ERRORES
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_ERRORES'))
    DROP PROCEDURE SP_OBTENER_ERRORES;
GO
-- Eliminar TB_HISTORIAL_COMPRAS
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_HISTORIAL_COMPRAS')
    DROP TABLE TB_HISTORIAL_COMPRAS;
GO
-- Eliminar TB_SOPORTES_CATEGORIAS
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_SOPORTES_CATEGORIAS')
    DROP TABLE TB_SOPORTES_CATEGORIAS;
GO
-- Eliminar TB_CATEGORIAS
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_CATEGORIAS')
    DROP TABLE TB_CATEGORIAS;
GO
-- ======================================================================================================
-- ELIMINAR LOS TRIGGERS
IF EXISTS (SELECT * FROM SYS.TRIGGERS WHERE NAME = 'TRG_VALIDAR_STOCK')
    DROP TRIGGER TRG_VALIDAR_STOCK;
GO
IF EXISTS (SELECT * FROM SYS.TRIGGERS WHERE NAME = 'TRG_ACTUALIZAR_FECHA_COMPRA')
    DROP TRIGGER TRG_ACTUALIZAR_FECHA_COMPRA;
GO
-- ======================================================================================================
-- ELIMINAR LOS STORED PROCEDURES
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INSERTAR_BITACORA'))
    DROP PROCEDURE SP_INSERTAR_BITACORA;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_REGISTRAR_FEEDBACK'))
    DROP PROCEDURE SP_REGISTRAR_FEEDBACK;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_LISTAR_PRODUCTOS'))
    DROP PROCEDURE SP_LISTAR_PRODUCTOS;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_LOGIN'))
    DROP PROCEDURE SP_LOGIN;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_REGISTRAR_PERSONA'))
    DROP PROCEDURE SP_REGISTRAR_PERSONA;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INSERTAR_PRODUCTO'))
    DROP PROCEDURE SP_INSERTAR_PRODUCTO;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INSERTAR_FEEDBACK'))
    DROP PROCEDURE SP_INSERTAR_FEEDBACK;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_FEEDBACK'))
    DROP PROCEDURE SP_OBTENER_FEEDBACK;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INGRESAR_VISITA'))
    DROP PROCEDURE SP_INGRESAR_VISITA;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_PRODUCTOS'))
    DROP PROCEDURE SP_OBTENER_PRODUCTOS;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_TICKET'))
    DROP PROCEDURE SP_OBTENER_TICKET;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INGRESAR_ERROR_BACKEND'))
    DROP PROCEDURE SP_INGRESAR_ERROR_BACKEND;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_ERRORES'))
    DROP PROCEDURE SP_OBTENER_ERRORES;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_TODOS_ERRORES'))
    DROP PROCEDURE SP_OBTENER_TODOS_ERRORES;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_HISTORIAL_VISITAS'))
    DROP PROCEDURE SP_OBTENER_HISTORIAL_VISITAS;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'ACTUALIZAR_CONTRASENA'))
    DROP PROCEDURE ACTUALIZAR_CONTRASENA;
GO
-- ======================================================================================================
-- ELIMINAR ÍNDICES EXISTENTES
IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX_TB_PERSONAS_CORREO')
    DROP INDEX IX_TB_PERSONAS_CORREO ON TB_PERSONAS;
GO
IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX_TB_PRODUCTOS_CATEGORIA')
    DROP INDEX IX_TB_PRODUCTOS_CATEGORIA ON TB_PRODUCTOS;
GO

IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX_TB_PRODUCTOS_USUARIO')
    DROP INDEX IX_TB_PRODUCTOS_USUARIO ON TB_PRODUCTOS;
GO

IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = 'IX_TB_FEEDBACK_PRODUCTO')
    DROP INDEX IX_TB_FEEDBACK_PRODUCTO ON TB_FEEDBACKS;
GO
-- ======================================================================================================
-- ELIMINAR LAS TABLAS EN ORDEN CORRECTO DEBIDO A LAS DEPENDENCIAS
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_MENSAJES_CHATS')
    DROP TABLE TB_MENSAJES_CHATS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_MENSAJES')
    DROP TABLE TB_MENSAJES;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_CHATS')
    DROP TABLE TB_CHATS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_RESPUESTAS_TICKETS')
    DROP TABLE TB_RESPUESTAS_TICKETS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_TICKETS')
    DROP TABLE TB_TICKETS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_SOPORTES_CATEGORIAS')
    DROP TABLE TB_SOPORTES_CATEGORIAS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_FEEDBACKS')
    DROP TABLE TB_FEEDBACKS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_HISTORIAL_VISITAS')
    DROP TABLE TB_HISTORIAL_VISITAS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_HISTORIAL_COMPRAS')
    DROP TABLE TB_HISTORIAL_COMPRAS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_CONVERSACIONES')
    DROP TABLE TB_CONVERSACIONES;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_PRODUCTOS')
    DROP TABLE TB_PRODUCTOS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_USUARIOS')
    DROP TABLE TB_USUARIOS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_CLIENTES')
    DROP TABLE TB_CLIENTES;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_CATEGORIAS')
    DROP TABLE TB_CATEGORIAS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_PERSONAS')
    DROP TABLE TB_PERSONAS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_BITACORAS')
    DROP TABLE TB_BITACORAS;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'ERRORES_BACKEND')
    DROP TABLE ERRORES_BACKEND;
GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_VERIFICACION')
    DROP TABLE TB_VERIFICACION;
GO
-- ======================================================================================================
-- TABLAS
-- TABLA PERSONAS
CREATE TABLE TB_PERSONAS (
    ID_PERSONA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE NVARCHAR(50) NOT NULL,
    CORREO NVARCHAR(55) NOT NULL UNIQUE,
    TELEFONO NVARCHAR(15) NULL,  -- Se añade el teléfono
    UBICACION geography NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),

);
GO
-- TABLA USUARIOS
CREATE TABLE TB_USUARIOS (
    ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
    ID_PERSONA INT NOT NULL FOREIGN KEY REFERENCES TB_PERSONAS(ID_PERSONA),
    ROL NVARCHAR(20) NOT NULL CHECK (ROL IN ('CLIENTE', 'VENDEDOR')),
    CONTRASENA NVARCHAR(128) NOT NULL,
    SEMILLA_1 NVARCHAR(128) NULL,
    SEMILLA_2 NVARCHAR(128) NULL,
    ESTADO BIT DEFAULT 1,  -- Se añade el estado
	FECHA_ULTIMA_COMPRA  DATETIME NULL
);
GO
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TB_CATEGORIAS')
    DROP TABLE TB_CATEGORIAS;
GO

-- TABLA PRODUCTOS
CREATE TABLE TB_PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY IDENTITY(1,1),
    ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES TB_USUARIOS(ID_USUARIO),
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(500),
    PRECIO DECIMAL(10,2) NOT NULL,
    PRECIO_ALQUILER DECIMAL(10,2),
    DISPONIBLE BIT DEFAULT 1,
    TIPO_OPERACION CHAR(1),
    STOCK INT DEFAULT 1,
    CALIFICACION_PROMEDIO DECIMAL(3,2) DEFAULT 0,
    FECHA_PUBLICACION DATETIME DEFAULT GETDATE(),
    CATEGORIA NVARCHAR(50) NULL,  -- Añadir la columna CATEGORIA
	IMAGEN NVARCHAR(255) NULL,  -- Se añade la imagen
	ID_CATEGORIA INT NULL,
    CONSTRAINT CHK_PRECIO CHECK (PRECIO >= 0),
    CONSTRAINT CHK_PRECIO_ALQUILER CHECK (PRECIO_ALQUILER >= 0 OR PRECIO_ALQUILER IS NULL),
    CONSTRAINT CHK_TIPO_OPERACION CHECK (TIPO_OPERACION IN ('V', 'A', 'B')),
    CONSTRAINT CHK_STOCK CHECK (STOCK >= 0)
);
GO
-- TABLA FEEDBACKS
CREATE TABLE TB_FEEDBACKS (
    ID_FEEDBACK INT PRIMARY KEY IDENTITY(1,1),
    ID_PRODUCTO INT NOT NULL FOREIGN KEY REFERENCES TB_PRODUCTOS(ID_PRODUCTO),
    ID_CLIENTE INT NOT NULL FOREIGN KEY REFERENCES TB_USUARIOS(ID_USUARIO),
    CALIFICACION DECIMAL(3,2) NOT NULL,
    COMENTARIO NVARCHAR(500),
    FECHA_FEEDBACK DATETIME DEFAULT GETDATE(),
    CONSTRAINT CHK_CALIFICACION_FEEDBACK CHECK (CALIFICACION >= 0 AND CALIFICACION <= 5)
);
GO
CREATE TABLE ERRORES_BACKEND(
	ID_Error INT PRIMARY KEY IDENTITY(1,1),
	Codigo_Error NVARCHAR(50) NOT NULL,
	Mensaje NVARCHAR(100) NOT NULL,
	Descripcion NVARCHAR(MAX) Not NULL,
	Resultado BIT NOT NULL DEFAULT 0,
	Fecha_Registro DATETIME DEFAULT GETDATE(),
);
GO
--ALGOLIA TABLAS
CREATE TABLE TB_HISTORIAL_VISITAS(
	ID_HISTORIAL_VISITAS INT PRIMARY KEY IDENTITY(1,1),
    ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES TB_USUARIOS(ID_USUARIO),
	ID_PRODUCTO INT NOT NULL FOREIGN KEY REFERENCES TB_PRODUCTOS(ID_PRODUCTO),
	FECHA_VISTA DATETIME DEFAULT GETDATE()
	);
	GO
--SIGNALR TABLAS
CREATE TABLE TB_CONVERSACIONES(
	ID_CONVERSACION INT PRIMARY KEY IDENTITY(1,1),
	ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES TB_USUARIOS(ID_USUARIO),
	ID_USUARIO2 INT NOT NULL FOREIGN KEY REFERENCES TB_USUARIOS(ID_USUARIO),
	FECHA_CREACION DATETIME DEFAULT GETDATE(),
	ES_SOPORTE BIT DEFAULT 0 
);
GO

CREATE TABLE TB_MENSAJES(
	ID_MENSAJES INT PRIMARY KEY IDENTITY(1,1),
	ID_CONVERSACION INT NOT NULL FOREIGN KEY REFERENCES TB_CONVERSACIONES(ID_CONVERSACION),
	ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES TB_USUARIOS(ID_USUARIO),
	MENSAJE NVARCHAR(700) NOT NULL ,
	FECHA_CREACION DATETIME DEFAULT GETDATE(),
	LEIDO BIT DEFAULT 0
);
GO

CREATE TABLE TB_VERIFICACION (
    ID_VERIFICACION INT PRIMARY KEY IDENTITY(1,1),  -- Clave primaria autoincremental
    CORREO NVARCHAR(55) NOT NULL,                  -- Correo electrónico del usuario
    CODEVERIFICACION NVARCHAR(10) NOT NULL,        -- Código de verificación
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),     -- Fecha de registro del código
	ESTADO BIT DEFAULT 1
);
GO

-- ======================================================================================================
-- ÍNDICES

CREATE NONCLUSTERED INDEX IX_TB_PERSONAS_CORREO ON TB_PERSONAS(CORREO);
GO

CREATE NONCLUSTERED INDEX IX_TB_PRODUCTOS_USUARIO ON TB_PRODUCTOS(ID_USUARIO);
GO

CREATE NONCLUSTERED INDEX IX_TB_FEEDBACK_PRODUCTO ON TB_FEEDBACKS(ID_PRODUCTO);
GO

-- ======================================================================================================
-- PROCEDIMIENTOS ALMACENADOS
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_REGISTRAR_USUARIO'))--Revisar el sp para que salga en el backen!!
    DROP PROCEDURE SP_REGISTRAR_USUARIO;
GO
--SP_REGISTRAR_USUARIO
CREATE PROCEDURE SP_REGISTRAR_USUARIO
    @NOMBRE NVARCHAR(50),
    @CORREO NVARCHAR(55),
    @TELEFONO NVARCHAR(15) = NULL,
    @ROL NVARCHAR(20),
    @CONTRASENA NVARCHAR(128),
    @SEMILLA_1 NVARCHAR(128) = NULL,
    @SEMILLA_2 NVARCHAR(128) = NULL,
    @ESTADO BIT = 1, 
    @ID_USUARIO INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    BEGIN TRANSACTION;

    BEGIN TRY
        -- Verificar si el correo ya existe
        IF EXISTS (SELECT 1 FROM TB_PERSONAS WHERE CORREO = @CORREO)
        BEGIN
            SET @ERRORID = 1;
            SET @ERRORDESCRIPCION = 'El correo ya está registrado.';
            ROLLBACK TRANSACTION;
            RETURN;
        END

        -- Insertar en TB_PERSONAS
        INSERT INTO TB_PERSONAS (NOMBRE, CORREO, TELEFONO)
        VALUES (@NOMBRE, @CORREO, @TELEFONO);

        SET @ID_USUARIO = SCOPE_IDENTITY();

        -- Insertar en TB_USUARIOS
        INSERT INTO TB_USUARIOS (ID_PERSONA, ROL, CONTRASENA, SEMILLA_1, SEMILLA_2, ESTADO)
        VALUES (@ID_USUARIO, @ROL, @CONTRASENA, @SEMILLA_1, @SEMILLA_2, @ESTADO);

        SET @ID_USUARIO = SCOPE_IDENTITY();

        -- Éxito
        SET @ERRORID = 0;
        SET @ERRORDESCRIPCION = 'Registro exitoso.';

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        SET @ERRORID = ERROR_NUMBER();
        SET @ERRORDESCRIPCION = ERROR_MESSAGE();
        ROLLBACK TRANSACTION;
    END CATCH;
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_LOGIN_USUARIO'))--Revisar el sp para que salga en el backen!!
    DROP PROCEDURE SP_LOGIN_USUARIO;
GO
-- SP_LOGIN     
CREATE PROCEDURE SP_LOGIN_USUARIO
	@CORREO NVARCHAR(55),
    @CONTRASENA NVARCHAR(128),
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    
    DECLARE @ID_PERSONA INT;
    DECLARE @ID_USUARIO INT;

    -- Validate input parameters
    IF @CORREO IS NULL OR @CONTRASENA IS NULL
    BEGIN
        SET @IDRETURN = -1;
        SET @ERRORID = 50001;
        SET @ERRORDESCRIPCION = 'Correo y contraseña son requeridos.';
        RETURN;
    END

    -- Find the persona by email
    SELECT 
        @ID_PERSONA = P.ID_PERSONA, 
        @ID_USUARIO = U.ID_USUARIO
    FROM TB_PERSONAS P
    INNER JOIN TB_USUARIOS U ON P.ID_PERSONA = U.ID_PERSONA
    WHERE P.CORREO = @CORREO 
      AND U.CONTRASENA = @CONTRASENA;

    -- Check if user exists
    IF @ID_PERSONA IS NULL
    BEGIN
        SET @IDRETURN = -1;
        SET @ERRORID = 50002;
        SET @ERRORDESCRIPCION = 'Correo o contraseña incorrectos.';
        RETURN;
    END

    -- Return user details for LINQ
        SELECT 
            U.ID_USUARIO AS ID_USUARIO,
            P.ID_PERSONA AS ID_PERSONA,
            P.NOMBRE AS NOMBRE,
            P.CORREO AS CORREO,
            P.TELEFONO AS TELEFONO,
            P.UBICACION AS UBICACION,
            U.ROL AS ROL,
            U.ESTADO AS ESTADO
        FROM TB_USUARIOS U
        INNER JOIN TB_PERSONAS P ON U.ID_PERSONA = P.ID_PERSONA
        WHERE U.ID_PERSONA = @ID_PERSONA

    -- Set success outputs
    SET @IDRETURN = @ID_USUARIO;
    SET @ERRORID = 0;
    SET @ERRORDESCRIPCION = 'Inicio de sesión exitoso.';
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_USUARIO'))--Revisar el sp para que salga en el backen!!
    DROP PROCEDURE SP_OBTENER_USUARIO;
GO
CREATE PROCEDURE SP_OBTENER_USUARIO
  @ID_USUARIO INT = NULL,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    -- If no ID is provided, return all active users
    IF @ID_USUARIO IS NULL
    BEGIN
        SELECT 
            U.ID_USUARIO AS IdUsuario,
            P.ID_PERSONA AS IdPersona,
            P.NOMBRE AS NOMBRE,
            P.CORREO AS CORREO,
            P.TELEFONO AS TELEFONO,
            U.ROL AS ROL,
            U.ESTADO AS ESTADO
        FROM TB_USUARIOS U
        INNER JOIN TB_PERSONAS P ON U.ID_PERSONA = P.ID_PERSONA
        WHERE U.ESTADO = 1;
    END
    ELSE
    BEGIN
        -- Buscar usuario específico
        SELECT 
            U.ID_USUARIO AS IdUsuario,
            P.ID_PERSONA AS IdPersona,
            P.NOMBRE AS NOMBRE,
            P.CORREO AS CORREO,
            P.TELEFONO AS TELEFONO,
            P.UBICACION AS UBICACION,
            U.ID_USUARIO AS ID_USUARIO,
            U.ROL AS ROL,
            U.ESTADO AS ESTADO,
            U.FECHA_ULTIMA_COMPRA AS FechaUltimaCompra
        FROM TB_USUARIOS U
        INNER JOIN TB_PERSONAS P ON U.ID_PERSONA = P.ID_PERSONA
        WHERE U.ID_USUARIO = @ID_USUARIO AND U.ESTADO = 1;
    END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'ACTUALIZAR_CONTRASENA'))--Revisar el sp para que salga en el backen!!
    DROP PROCEDURE ACTUALIZAR_CONTRASENA;
GO
CREATE PROCEDURE ACTUALIZAR_CONTRASENA
@CORREO NVARCHAR(55),          -- Correo del usuario
    @CONTRASENA NVARCHAR(128),     -- Nueva contraseña
    @SEMILLA_1 NVARCHAR(128),      -- Nueva semilla 1
    @SEMILLA_2 NVARCHAR(128),      -- Nueva semilla 2
    @IDRETURN INT OUTPUT,          -- Parámetro de salida para el ID del usuario
    @ERRORID INT OUTPUT,           -- Parámetro de salida para el código de error
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT -- Parámetro de salida para la descripción del error
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        -- Verificar si el correo existe en TB_PERSONAS
        IF NOT EXISTS (SELECT 1 FROM TB_PERSONAS WHERE CORREO = @CORREO)
        BEGIN
            -- Si el correo no existe, establecer los valores de salida para indicar el error
            SET @IDRETURN = -1; -- Indica que el correo no está registrado
            SET @ERRORID = 50002; -- Código de error personalizado
            SET @ERRORDESCRIPCION = 'El correo no está registrado.';
            RETURN;
        END;

        -- Obtener el ID_USUARIO asociado al correo
        DECLARE @ID_USUARIO INT;
        SELECT @ID_USUARIO = U.ID_USUARIO
        FROM TB_USUARIOS U
        INNER JOIN TB_PERSONAS P ON U.ID_PERSONA = P.ID_PERSONA
        WHERE P.CORREO = @CORREO;

        -- Actualizar la contraseña y las semillas en TB_USUARIOS
        UPDATE U
        SET 
            U.CONTRASENA = @CONTRASENA,
            U.SEMILLA_1 = @SEMILLA_1,
            U.SEMILLA_2 = @SEMILLA_2
        FROM TB_USUARIOS U
        INNER JOIN TB_PERSONAS P ON U.ID_PERSONA = P.ID_PERSONA
        WHERE P.CORREO = @CORREO;

        -- Establecer los valores de salida para indicar éxito
        SET @IDRETURN = @ID_USUARIO; -- Devuelve el ID del usuario actualizado
        SET @ERRORID = 0; -- Éxito
        SET @ERRORDESCRIPCION = 'Contraseña actualizada exitosamente.';
    END TRY
    BEGIN CATCH
        -- Manejar errores y establecer los valores de salida para indicar el error
        SET @IDRETURN = -1; -- Indica que ocurrió un error
        SET @ERRORID = ERROR_NUMBER(); -- Código de error de SQL Server
        SET @ERRORDESCRIPCION = ERROR_MESSAGE(); -- Mensaje de error de SQL Server
    END CATCH
END;
GO
-- SP_INSERTAR_PRODUCTO
CREATE PROCEDURE SP_INSERTAR_PRODUCTO
   @ID_USUARIO INT,
    @NOMBRE NVARCHAR(100),
    @DESCRIPCION NVARCHAR(500),
    @PRECIO DECIMAL(10,2),
    @PRECIO_ALQUILER DECIMAL(10,2) = NULL,
    @TIPO_OPERACION CHAR(1),
    @STOCK INT,
    @CATEGORIA NVARCHAR(50),
    @IMAGEN NVARCHAR(255) = NULL,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    -- Validar el tipo de operación
    IF @TIPO_OPERACION NOT IN ('V', 'A', 'B')
    BEGIN
        SET @IDRETURN = -1; -- Indica que el tipo de operación no es válido.
        SET @ERRORID = 50006; -- Código de error personalizado.
        SET @ERRORDESCRIPCION = 'El tipo de operación no es válido. Debe ser "V", "A" o "B".';
        RETURN;
    END;

    -- Insertar el producto
    INSERT INTO TB_PRODUCTOS (
        ID_USUARIO, NOMBRE, DESCRIPCION, PRECIO, PRECIO_ALQUILER, TIPO_OPERACION, STOCK, CATEGORIA, IMAGEN
    )
    VALUES (
        @ID_USUARIO, @NOMBRE, @DESCRIPCION, @PRECIO, @PRECIO_ALQUILER, @TIPO_OPERACION, @STOCK, @CATEGORIA, @IMAGEN
    );

    -- Obtener el ID del producto insertado
    SET @IDRETURN = SCOPE_IDENTITY();

    -- Devolver los datos del producto insertado
    SELECT 
        P.ID_PRODUCTO,
        P.ID_USUARIO,
        P.NOMBRE,
        P.DESCRIPCION,
        P.PRECIO,
        P.PRECIO_ALQUILER,
        P.TIPO_OPERACION,
        P.STOCK,
        P.DISPONIBLE,
        P.CALIFICACION_PROMEDIO,
        P.FECHA_PUBLICACION,
        P.IMAGEN,
        P.CATEGORIA  -- Ahora devuelve la categoría como NVARCHAR
    FROM TB_PRODUCTOS P
    WHERE P.ID_PRODUCTO = @IDRETURN;

    -- Establecer los valores de salida para indicar éxito
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Producto registrado exitosamente.';
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_LISTAR_PRODUCTOS_FILTRADOS'))--Revisar el sp para que salga en el backen!!
    DROP PROCEDURE SP_LISTAR_PRODUCTOS_FILTRADOS;
GO
-- SP_LISTAR_PRODUCTOS
CREATE PROCEDURE SP_LISTAR_PRODUCTOS_FILTRADOS
    @TIPO_OPERACION CHAR(1) = NULL,
    @PALABRA_CLAVE NVARCHAR(100) = NULL,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    SELECT 
        P.ID_PRODUCTO,
        P.NOMBRE,
        P.DESCRIPCION,
        P.PRECIO,
        P.PRECIO_ALQUILER,
        P.STOCK,
        P.TIPO_OPERACION,
        P.CALIFICACION_PROMEDIO,
        P.FECHA_PUBLICACION,
        P.ID_USUARIO,
        C.NOMBRE AS CATEGORIA
    FROM TB_PRODUCTOS P
    LEFT JOIN TB_PRODUCTOS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
    WHERE 
        P.DISPONIBLE = 1
        AND (@TIPO_OPERACION IS NULL OR P.TIPO_OPERACION IN (@TIPO_OPERACION, 'B'))
        AND (
            @PALABRA_CLAVE IS NULL 
            OR P.NOMBRE LIKE '%' + @PALABRA_CLAVE + '%' 
            OR P.DESCRIPCION LIKE '%' + @PALABRA_CLAVE + '%'
        )
    GROUP BY 
        P.ID_PRODUCTO, P.NOMBRE, P.DESCRIPCION, 
        P.PRECIO, P.PRECIO_ALQUILER, P.STOCK, P.TIPO_OPERACION,
        P.CALIFICACION_PROMEDIO, P.FECHA_PUBLICACION, P.ID_USUARIO, C.NOMBRE;

    SET @IDRETURN = 0; -- No se devuelve un ID específico.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Lista de productos obtenida exitosamente.';
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_LISTAR_PRODUCTO'))--Revisar el sp para que salga en el backen!!
    DROP PROCEDURE SP_LISTAR_PRODUCTO;
GO
CREATE PROCEDURE SP_LISTAR_PRODUCTO 
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        SELECT
            P.ID_PRODUCTO,
            P.NOMBRE,
            P.DESCRIPCION,
            P.PRECIO,
            P.PRECIO_ALQUILER,
            P.STOCK,
            P.TIPO_OPERACION,
            P.CALIFICACION_PROMEDIO,
            P.FECHA_PUBLICACION,
            P.DISPONIBLE,
            P.ID_USUARIO,
            C.NOMBRE AS CATEGORIA
        FROM TB_PRODUCTOS P
        LEFT JOIN TB_PRODUCTOS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
        ORDER BY P.FECHA_PUBLICACION DESC;
    END TRY
    BEGIN CATCH
        THROW;
    END CATCH
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_PRODUCTO'))--Revisar el sp para que salga en el backen!!
    DROP PROCEDURE SP_OBTENER_PRODUCTO;
GO
CREATE PROCEDURE SP_OBTENER_PRODUCTO --SP_OBTENER_PRODUCTO
    @ID_PRODUCTO INT,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM TB_PRODUCTOS WHERE ID_PRODUCTO = @ID_PRODUCTO)
    BEGIN
        SET @IDRETURN = -1; -- Indica que el producto no existe.
        SET @ERRORID = 50004; -- Código de error personalizado.
        SET @ERRORDESCRIPCION = 'El producto no existe.';
        RETURN;
    END;

    SELECT 
        P.ID_PRODUCTO,
        P.NOMBRE,
        P.DESCRIPCION,
        P.PRECIO,
        P.PRECIO_ALQUILER,
        P.STOCK,
        P.TIPO_OPERACION,
        P.CALIFICACION_PROMEDIO,
        P.FECHA_PUBLICACION,
        P.DISPONIBLE,
        P.ID_USUARIO,
        P.NOMBRE AS CATEGORIA
    FROM TB_PRODUCTOS P
    WHERE P.ID_PRODUCTO = @ID_PRODUCTO;

    SET @IDRETURN = @ID_PRODUCTO; -- Devuelve el ID del producto consultado.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Producto obtenido exitosamente.';
END;
GO
-- SP_INSERTAR_FEEDBACK
CREATE PROCEDURE SP_INSERTAR_FEEDBACK
   @ID_PRODUCTO INT,
    @ID_CLIENTE INT,
    @CALIFICACION DECIMAL(3,2),
    @COMENTARIO NVARCHAR(500) = NULL,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM TB_PRODUCTOS WHERE ID_PRODUCTO = @ID_PRODUCTO)
    BEGIN
        SET @IDRETURN = -1; -- Indica que el producto no existe.
        SET @ERRORID = 50004; -- Código de error personalizado.
        SET @ERRORDESCRIPCION = 'El producto no existe.';
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM TB_USUARIOS WHERE ID_USUARIO = @ID_CLIENTE)
    BEGIN
        SET @IDRETURN = -1; -- Indica que el cliente no existe.
        SET @ERRORID = 50005; -- Código de error personalizado.
        SET @ERRORDESCRIPCION = 'El cliente no existe.';
        RETURN;
    END;

    INSERT INTO TB_FEEDBACKS (ID_PRODUCTO, ID_CLIENTE, CALIFICACION, COMENTARIO)
    VALUES (@ID_PRODUCTO, @ID_CLIENTE, @CALIFICACION, @COMENTARIO);

    UPDATE P
    SET CALIFICACION_PROMEDIO = (
        SELECT AVG(CALIFICACION)
        FROM TB_FEEDBACKS
        WHERE ID_PRODUCTO = @ID_PRODUCTO
    )
    FROM TB_PRODUCTOS P
    WHERE P.ID_PRODUCTO = @ID_PRODUCTO;

    SET @IDRETURN = SCOPE_IDENTITY(); -- Devuelve el ID del feedback insertado.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Feedback registrado exitosamente.';
END;
GO
-- SP_OBTENER_FEEDBACK
CREATE PROCEDURE SP_OBTENER_FEEDBACK
    @ID_PRODUCTO INT = NULL,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    SELECT 
        F.ID_FEEDBACK,
        F.ID_PRODUCTO,
        P.NOMBRE AS NOMBRE_PRODUCTO,
        F.ID_CLIENTE AS ID_USUARIO,  -- Se añade el ID del cliente
        F.CALIFICACION,
        F.COMENTARIO,
        F.FECHA_FEEDBACK
    FROM TB_FEEDBACKS F
    JOIN TB_PRODUCTOS P ON F.ID_PRODUCTO = P.ID_PRODUCTO
    WHERE (@ID_PRODUCTO IS NULL OR F.ID_PRODUCTO = @ID_PRODUCTO)
    ORDER BY F.FECHA_FEEDBACK DESC;
    SET @IDRETURN = 0; -- No se devuelve un ID específico.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Feedback obtenido exitosamente.';
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INGRESAR_HISTORIAL_VISITA'))--Revisar el sp para que salga en el backen!!
    DROP PROCEDURE SP_INGRESAR_HISTORIAL_VISITA;
GO
--sp ingresar algolia
CREATE PROCEDURE SP_INGRESAR_HISTORIAL_VISITA  
   @ID_USUARIO INT,
    @ID_PRODUCTO INT,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT

AS
BEGIN
    IF EXISTS (SELECT 1 FROM TB_HISTORIAL_VISITAS WHERE ID_USUARIO = @ID_USUARIO AND ID_PRODUCTO = @ID_PRODUCTO)
    BEGIN
        DELETE FROM TB_HISTORIAL_VISITAS
        WHERE ID_USUARIO = @ID_USUARIO AND ID_PRODUCTO = @ID_PRODUCTO;
    END;

    INSERT INTO TB_HISTORIAL_VISITAS (ID_USUARIO, ID_PRODUCTO)
    VALUES (@ID_USUARIO, @ID_PRODUCTO);

    SET @IDRETURN = SCOPE_IDENTITY(); -- Devuelve el ID del registro insertado.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Visita registrada exitosamente.';
END;
GO
--SP INGRESAR SIGNALR
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INGRESAR_CONVERSACION'))
    DROP PROCEDURE SP_INGRESAR_CONVERSACION;
GO
CREATE PROCEDURE SP_INGRESAR_CONVERSACION  
   @ID_USUARIO INT,
    @ID_USUARIO2 INT,
    @ES_SOPORTE BIT = 0,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT

AS
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM TB_CONVERSACIONES 
        WHERE (ID_USUARIO = @ID_USUARIO AND ID_USUARIO2 = @ID_USUARIO2)
           OR (ID_USUARIO = @ID_USUARIO2 AND ID_USUARIO2 = @ID_USUARIO)
    )
    BEGIN
        SELECT @IDRETURN = ID_CONVERSACION
        FROM TB_CONVERSACIONES
        WHERE (ID_USUARIO = @ID_USUARIO AND ID_USUARIO2 = @ID_USUARIO2)
           OR (ID_USUARIO = @ID_USUARIO2 AND ID_USUARIO2 = @ID_USUARIO);

        SET @ERRORID = 0; -- Éxito.
        SET @ERRORDESCRIPCION = 'La conversación ya existe.';
        RETURN;
    END;

    INSERT INTO TB_CONVERSACIONES (ID_USUARIO, ID_USUARIO2, ES_SOPORTE)
    VALUES (@ID_USUARIO, @ID_USUARIO2, @ES_SOPORTE);

    SET @IDRETURN = SCOPE_IDENTITY(); -- Devuelve el ID de la conversación creada.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Conversación creada exitosamente.';
END;
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INGRESAR_MENSAJE'))
    DROP PROCEDURE SP_INGRESAR_MENSAJE;
GO
CREATE PROCEDURE SP_INGRESAR_MENSAJE 
@ID_CONVERSACION INT,
    @ID_USUARIO INT,
    @MENSAJE NVARCHAR(700),
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT

AS
BEGIN
    INSERT INTO TB_MENSAJES (ID_CONVERSACION, ID_USUARIO, MENSAJE)
    VALUES (@ID_CONVERSACION, @ID_USUARIO, @MENSAJE);

    SET @IDRETURN = SCOPE_IDENTITY(); -- Devuelve el ID del mensaje enviado.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Mensaje enviado exitosamente.';
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INGRESAR_ERROR_BACKEND'))--Revisar el sp para que salga en el backen!!
    DROP PROCEDURE SP_INGRESAR_ERROR_BACKEND;
GO
CREATE PROCEDURE SP_INGRESAR_ERROR_BACKEND
	@Codigo_Error NVARCHAR(50),
    @Mensaje NVARCHAR(MAX),
    @Descripcion NVARCHAR(MAX),
    @Resultado BIT,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT

AS
BEGIN
    INSERT INTO ERRORES_BACKEND (Codigo_Error, Mensaje, Descripcion, Resultado)
    VALUES (@Codigo_Error, @Mensaje, @Descripcion, @Resultado);

    SET @IDRETURN = SCOPE_IDENTITY(); -- Devuelve el ID del error registrado.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Error registrado exitosamente.';
END;
GO

--SP OBTENER ALGOLIA --Singular
CREATE PROCEDURE SP_OBTENER_HISTORIAL_VISITAS
 @ID_USUARIO INT = NULL,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT

AS
BEGIN
    SELECT 
        HV.ID_HISTORIAL_VISITAS,
        HV.ID_USUARIO,
        HV.ID_PRODUCTO,
        P.NOMBRE AS NOMBRE_PRODUCTO,
        HV.FECHA_VISTA
    FROM TB_HISTORIAL_VISITAS HV
    INNER JOIN TB_PRODUCTOS P ON HV.ID_PRODUCTO = P.ID_PRODUCTO
    WHERE @ID_USUARIO IS NULL OR HV.ID_USUARIO = @ID_USUARIO
    ORDER BY HV.FECHA_VISTA DESC;

    SET @IDRETURN = 0; -- No se devuelve un ID específico.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Historial de visitas obtenido exitosamente.';
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_CONVERSACION'))
    DROP PROCEDURE SP_OBTENER_CONVERSACION;
GO
CREATE PROCEDURE SP_OBTENER_CONVERSACION
 @ID_CONVERSACION INT,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    -- Obtener la información de la conversación
    SELECT 
        C.ID_CONVERSACION,
        C.ID_USUARIO AS ID_USUARIO1,
        C.ID_USUARIO2,  -- Se añade el ID del segundo usuario
        C.ES_SOPORTE,  -- Se añade el campo ES_SOPORTE
        C.FECHA_CREACION
    FROM TB_CONVERSACIONES C
    WHERE C.ID_CONVERSACION = @ID_CONVERSACION;

    SET @IDRETURN = @ID_CONVERSACION; -- Devuelve el ID de la conversación consultada.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Conversación obtenida exitosamente.';
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_LISTAR_CONVERSACIONES'))
    DROP PROCEDURE SP_LISTAR_CONVERSACIONES;
GO
CREATE PROCEDURE SP_LISTAR_CONVERSACIONES
    @ID_USUARIO INT,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT
AS
BEGIN
    -- Obtener la lista de conversaciones
    SELECT 
        C.ID_CONVERSACION,
        C.ID_USUARIO AS ID_USUARIO1,
        C.ID_USUARIO2,  -- Se añade el ID del segundo usuario
        C.ES_SOPORTE,  -- Se añade el campo ES_SOPORTE
        C.FECHA_CREACION
    FROM TB_CONVERSACIONES C
    WHERE C.ID_USUARIO = @ID_USUARIO OR C.ID_USUARIO2 = @ID_USUARIO
    ORDER BY C.FECHA_CREACION DESC;

    SET @IDRETURN = 0; -- No se devuelve un ID específico.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Lista de conversaciones obtenida exitosamente.';
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_LISTAR_MENSAJES'))
    DROP PROCEDURE SP_LISTAR_MENSAJES;
GO
CREATE PROCEDURE SP_LISTAR_MENSAJES
     @ID_CONVERSACION INT,
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT

AS
BEGIN
    UPDATE TB_MENSAJES
    SET LEIDO = 1
    WHERE ID_CONVERSACION = @ID_CONVERSACION
    AND LEIDO = 0;

    SELECT 
        M.ID_MENSAJES,
        M.ID_CONVERSACION,
        M.ID_USUARIO,
        P.NOMBRE AS NOMBRE_USUARIO,
        M.MENSAJE,
        M.FECHA_CREACION,
        M.LEIDO
    FROM TB_MENSAJES M
    INNER JOIN TB_USUARIOS U ON M.ID_USUARIO = U.ID_USUARIO
    INNER JOIN TB_PERSONAS P ON U.ID_PERSONA = P.ID_PERSONA
    WHERE M.ID_CONVERSACION = @ID_CONVERSACION
    ORDER BY M.FECHA_CREACION;

    SET @IDRETURN = @ID_CONVERSACION; -- Devuelve el ID de la conversación consultada.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Mensajes de la conversación obtenidos exitosamente.';
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_INSERTA_VERIFICACION'))--Revisar el sp para que salga en el backen!!
    DROP PROCEDURE SP_INSERTA_VERIFICACION;
GO
CREATE PROCEDURE SP_INSERTA_VERIFICACION
   @CORREO NVARCHAR(55),
    @CODEVERIFICACION NVARCHAR(10),
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT

AS
BEGIN
    IF EXISTS (SELECT 1 FROM TB_VERIFICACION WHERE CORREO = @CORREO)
    BEGIN
        UPDATE TB_VERIFICACION
        SET CODEVERIFICACION = @CODEVERIFICACION,
            FECHA_REGISTRO = GETDATE(),
            ESTADO = 1
        WHERE CORREO = @CORREO;
    END
    ELSE
    BEGIN
        INSERT INTO TB_VERIFICACION (CORREO, CODEVERIFICACION)
        VALUES (@CORREO, @CODEVERIFICACION);
    END;

    SET @IDRETURN = SCOPE_IDENTITY(); -- Devuelve el ID del registro insertado o actualizado.
    SET @ERRORID = 0; -- Éxito.
    SET @ERRORDESCRIPCION = 'Código de verificación registrado exitosamente.';
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_OBTENER_VERIFICACION'))
    DROP PROCEDURE SP_OBTENER_VERIFICACION;
GO
CREATE PROCEDURE SP_OBTENER_VERIFICACION
     @CORREO NVARCHAR(55),
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT

AS
BEGIN
    IF EXISTS (SELECT 1 FROM TB_VERIFICACION WHERE CORREO = @CORREO AND ESTADO = 1)
    BEGIN
        SELECT 
            ID_VERIFICACION,
            CORREO,
            CODEVERIFICACION,
            FECHA_REGISTRO
        FROM TB_VERIFICACION
        WHERE CORREO = @CORREO AND ESTADO = 1;

        SET @IDRETURN = SCOPE_IDENTITY(); -- Devuelve el ID del registro consultado.
        SET @ERRORID = 0; -- Éxito.
        SET @ERRORDESCRIPCION = 'Código de verificación obtenido exitosamente.';
    END
    ELSE
    BEGIN
        SET @IDRETURN = -1; -- Indica que no se encontró un código activo.
        SET @ERRORID = 50007; -- Código de error personalizado.
        SET @ERRORDESCRIPCION = 'No se encontró un código de verificación activo para el correo proporcionado.';
    END;
END;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SP_ELIMINAR_VERIFICACION'))
    DROP PROCEDURE SP_ELIMINAR_VERIFICACION;
GO
CREATE PROCEDURE SP_ELIMINAR_VERIFICACION
    @CORREO NVARCHAR(55),
    @IDRETURN INT OUTPUT,
    @ERRORID INT OUTPUT,
    @ERRORDESCRIPCION NVARCHAR(MAX) OUTPUT

AS
BEGIN
    IF EXISTS (SELECT 1 FROM TB_VERIFICACION WHERE CORREO = @CORREO)
    BEGIN
        DELETE FROM TB_VERIFICACION
        WHERE CORREO = @CORREO;

        SET @IDRETURN = 1; -- Indica que el registro fue eliminado.
        SET @ERRORID = 0; -- Éxito.
        SET @ERRORDESCRIPCION = 'Registro de verificación eliminado exitosamente.';
    END
    ELSE
    BEGIN
        SET @IDRETURN = -1; -- Indica que no se encontró el registro.
        SET @ERRORID = 50008; -- Código de error personalizado.
        SET @ERRORDESCRIPCION = 'No se encontró un registro de verificación para el correo proporcionado.';
    END;
END;
GO

-- ======================================================================================================
-- TRIGGERS

-- TRG_ACTUALIZAR_FECHA_COMPRA
CREATE TRIGGER TRG_ACTUALIZAR_FECHA_COMPRA
ON TB_PRODUCTOS
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    
    IF UPDATE(DISPONIBLE)
    BEGIN
        UPDATE U
        SET FECHA_ULTIMA_COMPRA = GETDATE()
        FROM TB_USUARIOS U
        INNER JOIN INSERTED I ON U.ID_USUARIO = I.ID_USUARIO
        WHERE I.DISPONIBLE = 0;
    END
END;
GO

-- TRG_VALIDAR_STOCK
CREATE TRIGGER TRG_VALIDAR_STOCK
ON TB_PRODUCTOS
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    
    IF UPDATE(STOCK)
    BEGIN
        UPDATE P
        SET DISPONIBLE = 
            CASE 
                WHEN I.STOCK > 0 THEN 1
                ELSE 0
            END
        FROM TB_PRODUCTOS P
        INNER JOIN INSERTED I ON P.ID_PRODUCTO = I.ID_PRODUCTO;
    END
END;
GO

-- Ejecutar SP_LOGIN_USUARIO
DECLARE @IDRETURN INT, @ERRORID INT, @ERRORDESCRIPCION NVARCHAR(MAX);
EXEC SP_LOGIN_USUARIO 
    @CORREO = 'carlos.lopez@example.com', 
    @CONTRASENA = 'clave123', 
    @IDRETURN = @IDRETURN OUTPUT, 
    @ERRORID = @ERRORID OUTPUT, 
    @ERRORDESCRIPCION = @ERRORDESCRIPCION OUTPUT;

PRINT 'IDRETURN: ' + CAST(@IDRETURN AS NVARCHAR);
PRINT 'ERRORID: ' + CAST(@ERRORID AS NVARCHAR);
PRINT 'ERRORDESCRIPCION: ' + @ERRORDESCRIPCION;
GO

-- Ejecutar SP_INSERTAR_FEEDBACK
DECLARE @IDRETURN INT, @ERRORID INT, @ERRORDESCRIPCION NVARCHAR(MAX);
EXEC SP_INSERTAR_FEEDBACK 
    @ID_PRODUCTO = 1, 
    @ID_CLIENTE = 1, 
    @CALIFICACION = 4.8, 
    @COMENTARIO = 'Excelente producto, muy rápido y eficiente.', 
    @IDRETURN = @IDRETURN OUTPUT, 
    @ERRORID = @ERRORID OUTPUT, 
    @ERRORDESCRIPCION = @ERRORDESCRIPCION OUTPUT;

PRINT 'IDRETURN: ' + CAST(@IDRETURN AS NVARCHAR);
PRINT 'ERRORID: ' + CAST(@ERRORID AS NVARCHAR);
PRINT 'ERRORDESCRIPCION: ' + @ERRORDESCRIPCION;
GO

-- Ejecutar SP_INGRESAR_HISTORIAL_VISITA
DECLARE @IDRETURN INT, @ERRORID INT, @ERRORDESCRIPCION NVARCHAR(MAX);
EXEC SP_INGRESAR_HISTORIAL_VISITA 
    @ID_USUARIO = 1, 
    @ID_PRODUCTO = 1, 
    @IDRETURN = @IDRETURN OUTPUT, 
    @ERRORID = @ERRORID OUTPUT, 
    @ERRORDESCRIPCION = @ERRORDESCRIPCION OUTPUT;

PRINT 'IDRETURN: ' + CAST(@IDRETURN AS NVARCHAR);
PRINT 'ERRORID: ' + CAST(@ERRORID AS NVARCHAR);
PRINT 'ERRORDESCRIPCION: ' + @ERRORDESCRIPCION;
GO

-- Ejecutar SP_OBTENER_PRODUCTO
DECLARE @IDRETURN INT, @ERRORID INT, @ERRORDESCRIPCION NVARCHAR(MAX);
EXEC SP_OBTENER_PRODUCTO 
    @ID_PRODUCTO = 1, 
    @IDRETURN = @IDRETURN OUTPUT, 
    @ERRORID = @ERRORID OUTPUT, 
    @ERRORDESCRIPCION = @ERRORDESCRIPCION OUTPUT;

PRINT 'IDRETURN: ' + CAST(@IDRETURN AS NVARCHAR);
PRINT 'ERRORID: ' + CAST(@ERRORID AS NVARCHAR);
PRINT 'ERRORDESCRIPCION: ' + @ERRORDESCRIPCION;
GO

-- Ejecutar SP_OBTENER_FEEDBACK
DECLARE @IDRETURN INT, @ERRORID INT, @ERRORDESCRIPCION NVARCHAR(MAX);
EXEC SP_OBTENER_FEEDBACK 
    @ID_PRODUCTO = 1, 
    @IDRETURN = @IDRETURN OUTPUT, 
    @ERRORID = @ERRORID OUTPUT, 
    @ERRORDESCRIPCION = @ERRORDESCRIPCION OUTPUT;

PRINT 'IDRETURN: ' + CAST(@IDRETURN AS NVARCHAR);
PRINT 'ERRORID: ' + CAST(@ERRORID AS NVARCHAR);
PRINT 'ERRORDESCRIPCION: ' + @ERRORDESCRIPCION;
GO

-- Ejecutar SP_OBTENER_HISTORIAL_VISITAS
DECLARE @IDRETURN INT, @ERRORID INT, @ERRORDESCRIPCION NVARCHAR(MAX);
EXEC SP_OBTENER_HISTORIAL_VISITAS 
    @ID_USUARIO = 1, 
    @IDRETURN = @IDRETURN OUTPUT, 
    @ERRORID = @ERRORID OUTPUT, 
    @ERRORDESCRIPCION = @ERRORDESCRIPCION OUTPUT;

PRINT 'IDRETURN: ' + CAST(@IDRETURN AS NVARCHAR);
PRINT 'ERRORID: ' + CAST(@ERRORID AS NVARCHAR);
PRINT 'ERRORDESCRIPCION: ' + @ERRORDESCRIPCION;
GO

-- Ejecutar SP_LISTAR_CONVERSACIONES
DECLARE @IDRETURN INT, @ERRORID INT, @ERRORDESCRIPCION NVARCHAR(MAX);
EXEC SP_LISTAR_CONVERSACIONES 
    @ID_USUARIO = 1, 
    @IDRETURN = @IDRETURN OUTPUT, 
    @ERRORID = @ERRORID OUTPUT, 
    @ERRORDESCRIPCION = @ERRORDESCRIPCION OUTPUT;

PRINT 'IDRETURN: ' + CAST(@IDRETURN AS NVARCHAR);
PRINT 'ERRORID: ' + CAST(@ERRORID AS NVARCHAR);
PRINT 'ERRORDESCRIPCION: ' + @ERRORDESCRIPCION;
GO

-- Ejecutar SP_INGRESAR_ERROR_BACKEND
DECLARE @IDRETURN INT, @ERRORID INT, @ERRORDESCRIPCION NVARCHAR(MAX);
EXEC SP_INGRESAR_ERROR_BACKEND 
    @Codigo_Error = 'ERR-001', 
    @Mensaje = 'Error de conexión a la base de datos', 
    @Descripcion = 'No se pudo conectar al servidor SQL', 
    @Resultado = 0, 
    @IDRETURN = @IDRETURN OUTPUT, 
    @ERRORID = @ERRORID OUTPUT, 
    @ERRORDESCRIPCION = @ERRORDESCRIPCION OUTPUT;

PRINT 'IDRETURN: ' + CAST(@IDRETURN AS NVARCHAR);
PRINT 'ERRORID: ' + CAST(@ERRORID AS NVARCHAR);
PRINT 'ERRORDESCRIPCION: ' + @ERRORDESCRIPCION;
GO

-- Ejecutar SP_ELIMINAR_VERIFICACION
DECLARE @IDRETURN INT, @ERRORID INT, @ERRORDESCRIPCION NVARCHAR(MAX);
EXEC SP_ELIMINAR_VERIFICACION 
    @CORREO = 'carlos.lopez@example.com', 
    @IDRETURN = @IDRETURN OUTPUT, 
    @ERRORID = @ERRORID OUTPUT, 
    @ERRORDESCRIPCION = @ERRORDESCRIPCION OUTPUT;

PRINT 'IDRETURN: ' + CAST(@IDRETURN AS NVARCHAR);
PRINT 'ERRORID: ' + CAST(@ERRORID AS NVARCHAR);
PRINT 'ERRORDESCRIPCION: ' + @ERRORDESCRIPCION;
GO