//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatosMovil.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CompuSebas\\SQLEXPRESS;Initial Catalog=QUERY_MOVIL_V3;Integrated Secur" +
            "ity=True;Encrypt=False")]
        public string QUERY_MOVIL_V3ConnectionString {
            get {
                return ((string)(this["QUERY_MOVIL_V3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YOUR_DB_SERVER;Initial Catalog=QUERY_MOVIL_V2;User ID=YOUR_DB_USER;Password=YOUR_DB_PASSWORD;")]
        public string QUERY_MOVIL_V2ConnectionString {
            get {
                return ((string)(this["QUERY_MOVIL_V2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YOUR_DB_SERVER;Initial Catalog=QUERY_MOVIL_V2;User ID=YOUR_DB_USER;Password=YOUR_DB_PASSWORD")]
        public string QUERY_MOVIL_V2ConnectionString1 {
            get {
                return ((string)(this["QUERY_MOVIL_V2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CompuSebas\\SQLEXPRESS;Initial Catalog=QUERY_MOVIL_V2;Integrated Secur" +
            "ity=True;Encrypt=False")]
        public string QUERY_MOVIL_V2ConnectionString2 {
            get {
                return ((string)(this["QUERY_MOVIL_V2ConnectionString2"]));
            }
        }
    }
}
